from pathlib import Path

p = Path('/home/ubuntu/goyo-korean-app/client/src/lib/alphabet.ts')
rows = [
('cons_001','ㄱ','g/k','기역','기역','가 (ga - house)','consonant'),('cons_002','ㄴ','n','니은','니은','나 (na - I)','consonant'),('cons_003','ㄷ','d/t','디귿','디귿','다 (da - all)','consonant'),('cons_004','ㄹ','r/l','리을','리을','라 (ra - pull)','consonant'),('cons_005','ㅁ','m','미음','미음','마 (ma - horse)','consonant'),('cons_006','ㅂ','b/p','비읍','비읍','바 (ba - wind)','consonant'),('cons_007','ㅅ','s','시옷','시옷','사 (sa - four)','consonant'),('cons_008','ㅇ','ng','이응','이응','아 (a - I)','consonant'),('cons_009','ㅈ','j','지읒','지읒','자 (ja - self)','consonant'),('cons_010','ㅊ','ch','치읓','치읓','차 (cha - car)','consonant'),('cons_011','ㅋ','k','키읔','키읔','카 (ka - card)','consonant'),('cons_012','ㅌ','t','티읕','티읕','타 (ta - other)','consonant'),('cons_013','ㅍ','p','피읖','피읖','파 (pa - wave)','consonant'),('cons_014','ㅎ','h','히읗','히읗','하 (ha - do)','consonant'),('cons_015','ㄲ','kk','쌍기역','쌍기역','까 (kka - peel)','consonant'),('cons_016','ㄸ','tt','쌍디귿','쌍디귿','따 (tta - follow)','consonant'),('cons_017','ㅃ','pp','쌍비읍','쌍비읍','빠 (ppa - fast)','consonant'),('cons_018','ㅆ','ss','쌍시옷','쌍시옷','싸 (ssa - cheap)','consonant'),('cons_019','ㅉ','jj','쌍지읒','쌍지읒','짜 (jja - salty)','consonant'),
('vowel_001','ㅏ','a','아','아','아 (a - I)','vowel'),('vowel_002','ㅑ','ya','야','야','야 (ya - hey)','vowel'),('vowel_003','ㅓ','eo','어','어','어 (eo - uh)','vowel'),('vowel_004','ㅕ','yeo','여','여','여 (yeo - woman)','vowel'),('vowel_005','ㅗ','o','오','오','오 (o - five)','vowel'),('vowel_006','ㅛ','yo','요','요','요 (yo - ending)','vowel'),('vowel_007','ㅜ','u','우','우','우 (u - rain)','vowel'),('vowel_008','ㅠ','yu','유','유','유 (yu - oil)','vowel'),('vowel_009','ㅡ','eu','으','으','으 (eu - sound)','vowel'),('vowel_010','ㅣ','i','이','이','이 (i - this)','vowel'),('vowel_011','ㅐ','ae','애','애','애 (ae - child)','vowel'),('vowel_012','ㅒ','yae','얘','얘','얘 (yae - this person)','vowel'),('vowel_013','ㅔ','e','에','에','에 (e - at)','vowel'),('vowel_014','ㅖ','ye','예','예','예 (ye - yes)','vowel'),('vowel_015','ㅘ','wa','와','와','와 (wa - wow)','vowel'),('vowel_016','ㅙ','wae','왜','왜','왜 (wae - why)','vowel'),('vowel_017','ㅚ','oe','외','외','외 (oe - outside)','vowel'),('vowel_018','ㅝ','wo','워','워','워 (wo - sound)','vowel'),('vowel_019','ㅞ','we','웨','웨','웨 (we - way)','vowel'),('vowel_020','ㅟ','wi','위','위','위 (wi - above)','vowel'),('vowel_021','ㅢ','ui','의','의','의 (ui - of)','vowel'),
]
out = ['export interface AlphabetCard { id: string; hangul: string; romanization: string; sound: string; ttsText: string; example: string; type: "consonant" | "vowel"; }', '', 'export const ALPHABET_DATA: AlphabetCard[] = [']
for r in rows:
    out.append(f'  {{ id: "{r[0]}", hangul: "{r[1]}", romanization: "{r[2]}", sound: "{r[3]}", ttsText: "{r[4]}", example: "{r[5]}", type: "{r[6]}" }},')
out += ['];', '', 'export const ALPHABET_CATEGORIES = [', '  { id: "consonants", name: "Consonants", icon: "🔤", color: "bg-blue-100 text-blue-700" },', '  { id: "vowels", name: "Vowels", icon: "🎵", color: "bg-purple-100 text-purple-700" },', '];', '', 'export const ALPHABET_COUNTS = { consonants: 19, vowels: 21, total: 40 } as const;', 'export const ALPHABET_CATEGORY_DESCRIPTIONS = { consonants: "19 consonants · 14 basic + 5 double consonants", vowels: "21 vowels · 10 basic + 11 combined vowels" } as const;', 'export const ALPHABET_FULL_INVENTORY_LABEL = "Full modern Hangul inventory · 40 characters";', 'export const ALPHABET_AUDIO_VOICE = "Hyuk - Cold and Clear";', 'export const ALPHABET_AUDIO_VOICE_ID = "ZJCNdZEjYwkOElxugmW2";', 'export const ALPHABET_AUDIO_MODEL = "eleven_multilingual_v2";', 'export const ALPHABET_TTS_MODE = "letter-name" as const;', 'export const ALPHABET_AUDIO_TEXT: Record<string, string> = Object.fromEntries(ALPHABET_DATA.map((card) => [card.id, card.ttsText]));', 'export const ALPHABET_CONSONANT_CARDS = ALPHABET_DATA.filter((card) => card.type === "consonant");', 'export const ALPHABET_VOWEL_CARDS = ALPHABET_DATA.filter((card) => card.type === "vowel");', 'export const ALPHABET_CARD_LOOKUP = Object.fromEntries(ALPHABET_DATA.map((card) => [card.id, card]));', 'export const ALPHABET_TOTAL = ALPHABET_DATA.length;', 'export const ALPHABET_CONSONANT_TOTAL = ALPHABET_CONSONANT_CARDS.length;', 'export const ALPHABET_VOWEL_TOTAL = ALPHABET_VOWEL_CARDS.length;', 'export const ALPHABET_DATASET_IS_COMPLETE = ALPHABET_TOTAL === 40 && ALPHABET_CONSONANT_TOTAL === 19 && ALPHABET_VOWEL_TOTAL === 21;', 'export const ALPHABET_LEARNING_NOTE = "Consonants are pronounced by their Korean letter names; for example, ㄴ is 니은 (nieun).";', '', 'export function getAlphabetAudioText(characterId: string): string { return ALPHABET_AUDIO_TEXT[characterId] ?? characterId; }', 'export function getAlphabetCardCount(type: "consonants" | "vowels"): number { return type === "consonants" ? ALPHABET_CONSONANT_TOTAL : ALPHABET_VOWEL_TOTAL; }', 'export function getAlphabetCards(type: "consonants" | "vowels"): AlphabetCard[] { return type === "consonants" ? ALPHABET_CONSONANT_CARDS : ALPHABET_VOWEL_CARDS; }', '']
p.write_text('\n'.join(out), encoding='utf-8')
print(f'wrote {p} with {len(rows)} cards and {len(out)} lines')
